"""create tables

Revision ID: d4abaa8e3df4
Revises: 
Create Date: 2025-06-13 19:49:30.031669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4abaa8e3df4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'])
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###
